=head1 SYNOPSIS

iCPAN is the CPAN on your iPhone/iPod/iPad. For a full description of what
iCPAN is, please see the iCPAN app store page:
L<http://itunes.apple.com/app/icpan/id377340561?mt=8>

=head1 GETTING STARTED

=head2 INSTALL THE SDK

To edit the code and/or deploy to your iDevice, you'll first need to install
the iPhone SDK: L<http://developer.apple.com/iphone/index.action>

=head2 GET THE CODE

You can either clone the main repository:

    git clone git@github.com:oalders/iCPAN.git

Or, you can fork this on GitHub and then clone your own fork of the repo.  This
would be the recommended way of doing things:

    git clone git@github.com:yournamehere/iCPAN.git

You'll also need to get the submodules:

    cd iCPAN
    git submodule init
    git submodule update

=head2 GET THE DATABASE

You can find the database snapshots at:
L<http://icpan.wundercounter.com/sqlite> The folders are organized by version
number. Download the iCPAN.sqlite.zip file in the appropriate folder, unzip it
and copy it into your top iCPAN folder. For example, to download the code for
the very latest version of the code:

    cd iCPAN
    curl -C - -O http://icpan.wundercounter.com/sqlite/latest/iCPAN.sqlite.zip
    unzip iCPAN.sqlite.zip

To work with a tagged release, like version 1.0.0:

    cd iCPAN
    git checkout -b v1.0.0 v1.0.0
    curl -C - -O http://icpan.wundercounter.com/sqlite/1.0.0/iCPAN.sqlite.zip
    unzip iCPAN.sqlite.zip


=head2 BUILD AND RUN

At this point, you can click the Xcode "Build and Run" button to deploy the
app to your iPhone simulator.

=head3 TROUBLESHOOTING

If you run into problems deploying to the simulator after altering the
database, try resetting it and then building again. "iPhone Simulator" ->
"Reset Content and Settings"

If GRMustache throws an "unrecognized selector" error, check the
"Other Linker Flags" in your "Build Settings". Select "Any iOS" when
deploying to hardware.  Select "Any iOS Simulator" when deploying to
the simulator.

=head1 CONTACT

There is currently no mailing list. If you have any questions, feel free to
send a message via GitHub. You can also follow us on Twitter for updates:

L<http://twitter.com/wundercounter>

L<http://twitter.com/ioncache>
