=head1 SYNOPSIS

iCPAN is CPAN on your iPhone.  For a full description of what iCPAN is,
please see the iCPAN app store
page: B<http://itunes.apple.com/app/icpan/id377340561?mt=8

=head1 GETTING STARTED

To edit the code and/or deploy to your iPhone/iPod/iPad, you'll need to install
the iPhone SDK: B<http://developer.apple.com/iphone/index.action>

After installing the SDK and cloning this repository, you'll need to add the
iCPAN.sqlite database to your project. To do so, in your XCode project,
ctrl-click on the Resources folder. Choose "Add" -> "Existing Files". Choose
the sqlite file. You will then be presented with a list of options for adding
the file. You should be fine to accept the defaults.

At this point, you can click the Xcode "Build and Run" button to deploy the
app to your iPhone simulator.  
