=head1 SYNOPSIS

The /website directory is the home of the Dancer app, which can be used to
test generated POD.  It's also the site which is located at 
http://icpan.wundercounter.com

=head1 REQUIRED CPAN MODULES

You can easily install all required CPAN modules with the install/cpan_modules
script.

    sh website/install/cpan_modules.sh

However, before you do this, please make sure you've installed all of the
modules required in the /perl directory.  

    sh perl/install/cpan_modules.sh

If you run into errors, try installing the very latest versions of the
modules listed in these files, particularly Dancer and DBIx::Class::Schema::Loader.

=head1 GET THE DATABASE 

See the README in the top level of the repository for more info on downloading
the correct database. 

=head1 GETTING UP AND RUNNING

A simple way to deploy the site would be the following:

    perl website/iCPAN-web.pl 

Which yields:

    >> Dancer server 3628 listening on http://0.0.0.0:3000
    == Entering the development dance floor ...

You may then test out documentation in the following way:

    http://localhost:3000/docs/HTTP::BrowserDetect

For more info on this deployment script:

    perl website/iCPAN-web.pl --help

